"""add onboarding fields to user_account

Revision ID: 9facba9aaefb
Revises: ad06379323a2
Create Date: 2026-08-12 12:44:58.440212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9facba9aaefb'
down_revision: Union[str, Sequence[str], None] = 'ad06379323a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('subject_name', sa.String(length=255), nullable=True))
    op.add_column('user_account', sa.Column('subject_relationship', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'subject_relationship')
    op.drop_column('user_account', 'subject_name')
    # ### end Alembic commands ###
